apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- gateway.yaml

namespace: auraweb-dev

namePrefix: dev-

commonLabels:
  environment: development

images:
- name: frontend
  newName: yassine09/lab-frontend
  newTag: 3e91398ed835f4f528665dd5a8c7aaa54e091769
- name: user-auth
  newName: yassine09/lab-auth
  newTag: 3e91398ed835f4f528665dd5a8c7aaa54e091769
