apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- gateway.yaml

namespace: auraweb-dev

namePrefix: dev-

commonLabels:
  environment: development

images:
- name: frontend
  newName: yassine09/lab-frontend
  newTag: 943c74904d2c94771a4a594daef3f622a7f0d9fe
- name: user-auth
  newName: yassine09/lab-auth
  newTag: 943c74904d2c94771a4a594daef3f622a7f0d9fe
- name: yassine09/lab-auth
  newName: yassine09/lab-auth
  newTag: a613e1f70a390db760c314b78cfd97fd0098c751
- name: yassine09/lab-frontend
  newName: yassine09/lab-frontend
  newTag: a613e1f70a390db760c314b78cfd97fd0098c751
