apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- gateway.yaml

namespace: auraweb-prod

commonLabels:
  environment: production

images:
- name: frontend
  newName: yassine09/lab-frontend
  newTag: cc0b3864aad3617047b486f77e8dc5c918a0cab6
- name: user-auth
  newName: yassine09/lab-auth
  newTag: cc0b3864aad3617047b486f77e8dc5c918a0cab6

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
  target:
    kind: Deployment
