apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- gateway.yaml

namespace: auraweb-prod

commonLabels:
  environment: production


images:
- name: yassine09/lab-auth
  newName: yassine09/lab-auth
  newTag: 957561c57a88ec6b89799d7d2307103563e61a8d
- name: yassine09/lab-frontend
  newName: yassine09/lab-frontend
  newTag: 957561c57a88ec6b89799d7d2307103563e61a8d

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
  target:
    kind: Deployment
