apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- gateway.yaml

namespace: auraweb-prod

commonLabels:
  environment: production


images:
- name: yassine09/lab-auth
  newName: yassine09/lab-auth
  newTag: ce3000ef6f2b3981c82a9c1a83e5a14e84ee7abe
- name: yassine09/lab-frontend
  newName: yassine09/lab-frontend
  newTag: ce3000ef6f2b3981c82a9c1a83e5a14e84ee7abe

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
  target:
    kind: Deployment
