apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-backend
  namespace: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-backend
  template:
    metadata:
      labels:
        app: auth-backend
    spec:
      nodeSelector:
        role: app
      imagePullSecrets:
      - name: dockerhub-creds
      containers:
      - name: auth-backend
        image: yassine09/lab-auth:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: PORT
          value: "3000"
        - name: DB_HOST
          value: "postgres"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD
        - name: JWT_SECRET
          value: "changeme-lab-jwt-secret"
        - name: REDIS_HOST
          value: "redis"
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq:5672"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          failureThreshold: 30
          periodSeconds: 10
