apiVersion: apps/v1
kind: Deployment
metadata:
  name: fulfillment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fulfillment
  template:
    metadata:
      labels:
        app: fulfillment
    spec:
      containers:
      - name: fulfillment
        image: yassine09/lab-fulfillment:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 3003
        env:
        - name: PORT
          value: "3003"
        - name: DB_HOST
          value: "postgres"
        - name: REDIS_HOST
          value: "redis"
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq:5672"
        envFrom:
        - secretRef:
            name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: fulfillment
spec:
  selector:
    app: fulfillment
  ports:
  - port: 3003
    targetPort: 3003
