apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-statefulset.yaml
  - redis-deployment.yaml
  - rabbitmq-deployment.yaml
  - frontend-deployment.yaml
  - admin-deployment.yaml
  - catalog-deployment.yaml
  - inventory-deployment.yaml
  - shopping-deployment.yaml
  - order-payment-deployment.yaml
  - fulfillment-deployment.yaml
  - user-auth-deployment.yaml
  - platform-deployment.yaml

secretGenerator:
  - name: app-secrets
    literals:
      - APP_SECRET=devsecret
      - POSTGRES_PASSWORD=devpassword
      - REDIS_PASSWORD=devpassword
      - RABBITMQ_DEFAULT_PASS=devpassword

generatorOptions:
  disableNameSuffixHash: true